`thread::spawn`, Send, Arc, Mutex
ferrous-systems/rust-training pull request #119
Opened 2024-01-22 14:29 UTC by listochkin

2024-01-22 17:42 UTC, jonathanpallant requested changes
This is great! Just some minor nits.

2024-01-22 17:42 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +## `tread::spawn` Function
```suggestion
## `thread::spawn` Function
```

2024-01-22 17:42 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +  * data the closure *closes over* / *captures*: **Upvars**
oooh, TIL. We should call them that in the closures deck.

2024-01-22 17:42 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +One of two cases:
Perhaps:

```suggestion
Two allowable options:
```

2024-01-22 17:42 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +* applies to data passed from parent thread to child thread or vise versa
```suggestion
* applies to data passed from parent thread to child thread or vice-versa
```

2024-01-22 17:42 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +  * `+ 'static` lets borrow checker detect these situations at compile time
```suggestion
  * `+ 'static` avoids this by ensuring any references point to data that has the static lifetime (i.e. that lives forever)
```

2024-01-22 17:42 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +  * precaution measure
```suggestion
  * precautionary measure
```

2024-01-22 17:42 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +* Rust pointers (`*const T`, `*mut T`, `NonNull<T>`) are `!Send`
~~Also, `UnsafeCell` is !Send, if I remember right.~~

It's Send but !Sync.

2024-01-22 17:42 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +* Rust compiler has to inherent knowledge of threads, but the use of marker traits and lifetime annotations let the type / borrow checker prevent data race errors
```suggestion
* Rust compiler has no inherent knowledge of threads, but the use of marker traits and lifetime annotations let the type / borrow checker prevent data race errors
```

2024-01-22 17:42 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +* With the help of marker trait `Send` and trait bounds on `thread::spawn` Rust compiler *forces* you to use the correct type
Perhaps:

```suggestion
* With the help of marker trait `Send` and trait bounds on `thread::spawn`, the compiler *forces* you to use the correct type
```

2024-01-22 17:42 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +* careful use of traits and trait boundaries lets Rust compiler detect problematic multithreading code at compile time
```suggestion
* careful use of traits and trait boundaries lets the compiler detect problematic multi-threading code at compile time
```

Or *the Rust compiler*

2024-02-05 16:35 UTC, jonathanpallant commented on training-slides/src/SUMMARY.md
> +* [Deconstructing Send, Arc, and Mutex](./deconstructing-send-arc-mutex.md)
```suggestion
* [Deconstructing Send, Arc, and Mutex](./deconstructing-send-arc-mutex.md)

```

Is it under development, or is it done now?

2024-07-01 13:55 UTC, miguelraz approved these changes

2024-07-01 14:18 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +* `let mut thread_log = log.clone()` now does't clone the data, but simply increases the reference count
```suggestion
* `let mut thread_log = log.clone()` now doesn't clone the data, but simply increases the reference count
```

2024-07-01 14:25 UTC, jonathanpallant commented on training-slides/src/deconstructing-send-arc-mutex.md
> +## Critical Section "Hygiene"
This slide didn't fit on my screen :(

2024-07-01 14:26 UTC, jonathanpallant commented
couple of typos and one slide that didn't fit (I love the Cloudflare test deployments!)

2024-09-03 16:06 UTC, jonathanpallant approved these changes

2024-09-03 16:06 UTC, merged