setup xtask infra for cheatsheets
ferrous-systems/rust-training pull request #159
Opened 2024-06-10 22:21 UTC by miguelraz

This should address our concerns on maintainability of a `cheatsheet` folder.

This is a draft for now 
```
❯ cargo xtask make-cheatsheet julia
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
     Running `target\debug\xtask.exe make-cheatsheet julia`
make_cheatsheet for julia
```

Just wanted to get early feedback on an `xtask` setup for this.

2024-06-13 08:12 UTC, jonathanpallant commented
Could we add a few words (here, or in a README) about how the cheatsheets work - to save having to read and understand the source code?

2024-06-13 08:13 UTC, jonathanpallant commented
Also, it needs a rebase on `main` to fix the CloudFlare CI failure, and some thought about the workspaces to fix the GHA CI failure.

2024-06-13 14:40 UTC, miguelraz commented
@jonathanpallant 

* added a README.md
* rebased to main to have Cloudflare deploy passing
* fixed workspace issue by adding a `exclude = ["examples/"]` array to the `Cargo.toml` and CI is happy

2024-07-01 08:51 UTC, jonathanpallant commented on xtask/README.md
> +As `training-material` grows and changes, maintenance could be a nightmare. We basically don't want to be in the business of remember that a certain slide got reordered or moved from one section to a
```suggestion
As `training-material` grows and changes, maintenance could be a nightmare. We basically don't want to be in the business of remembering that a certain slide got reordered or moved from one section to another and thus needs changing in all the cheatsheets as well. Therefore, this tool seeks to alleviate that with the following workflow:
```

2024-07-01 08:51 UTC, jonathanpallant commented on xtask/README.md
> +* scrape Markdown headers in `SUMMARY.md` and segment topics by `Rust Fundamentals`, `Applied Rust` and `Advanced Rust`
Who does this - the user or the tool? Because step 1 in this list is something the user has to do.

2024-07-01 08:53 UTC, jonathanpallant commented on xtask/src/main.rs
> +    let args = args.iter().map(|arg| &arg[..]).collect::<Vec<_>>();
What is this line for? `args` is already a `Vec<String>` right?

2024-07-01 08:54 UTC, jonathanpallant commented on xtask/src/main.rs
> +        panic!("{} is not a valid language name. \nExpected one of: python, go, cpp, swift, java, julia, c", &args[1]);
I'd print the lang list in the panic so it doesn't get out of sync.

2024-07-01 08:56 UTC, jonathanpallant commented on xtask/src/tasks.rs
> +fn test_get_slide_name() {
Tests should go in a `#[cfg(test)] mod test { ... }`

2024-07-01 08:58 UTC, jonathanpallant commented on xtask/src/tasks.rs
> +    let first_header = text.find(INITIAL_HEADER).unwrap();
You can handle the error here rather than having a separate `contains` check which might get isolated from this line.

```rust
let Some(first_header) = text.find(INITIAL_HEADER) else {
    panic!("Could not find the initial header {INITIAL_HEADER:?}. Check your `SUMMARY.md`");
}
```

2024-07-01 08:59 UTC, jonathanpallant commented on xtask/src/tasks.rs
> +fn test_focus_regions() {
Tests should go in a #[cfg(test)] mod test { ... }

2024-07-01 09:00 UTC, jonathanpallant commented on xtask/src/tasks.rs
> +fn test_extract_slides() {
Tests should go in a #[cfg(test)] mod test { ... }

2024-07-01 09:02 UTC, jonathanpallant commented
OK, I think this tool makes sense. I had some minor points about the program itself, but I also think we should be running the unit tests in CI, and testing our cheat-sheets in CI.

2024-07-01 14:01 UTC, miguelraz commented on xtask/src/main.rs
> +    let langs = vec!["python", "go", "cpp", "swift", "java", "julia", "c"];
Yup!

2024-07-03 08:47 UTC, jonathanpallant commented
re-assign to me when you're ready, thanks!

2024-12-24 04:50 UTC, miguelraz commented on xtask/README.md
> +* scrape Markdown headers in `SUMMARY.md` and segment topics by `Rust Fundamentals`, `Applied Rust` and `Advanced Rust`
Yes, for now it's the user's responsibility to run the check after modifying any of the cheatsheets - I wouldn't mind doing a follow up PR that adds it to the build scripts. I'll add that as a follow up task for myself on Clickup.

2024-12-24 05:04 UTC, miguelraz commented on xtask/src/main.rs
> +    let langs = vec!["python", "go", "cpp", "swift", "java", "julia", "c"];
Done.

2024-12-24 05:12 UTC, miguelraz commented on xtask/src/main.rs
> +                "cargo xtask
Good call, done.

2024-12-24 05:29 UTC, miguelraz commented on xtask/src/main.rs
> +        panic!("{} is not a valid language name. \nExpected one of: python, go, cpp, swift, java, julia, c", &args[1]);
Good call, added that and some cleaner formatting in the print.

2024-12-24 05:41 UTC, miguelraz commented on xtask/src/tasks.rs
> +fn test_get_slide_name() {
Neater, done.

2024-12-24 05:41 UTC, miguelraz commented on xtask/src/tasks.rs
> +fn test_focus_regions() {
Also refactored, thanks.

2024-12-24 05:43 UTC, miguelraz commented on xtask/src/tasks.rs
> +fn test_extract_slides() {
Also refactored.

2024-12-24 05:52 UTC, miguelraz commented on xtask/src/tasks.rs
> +    let first_header = text.find(INITIAL_HEADER).unwrap();
Oh, that is a much nicer form. Done.

2024-12-24 06:12 UTC, miguelraz commented
Force pushed to get rid of a pesky rebase muddying the history horribly.

2024-12-24 06:20 UTC, miguelraz commented
Should be ready for review again.

2025-01-06 15:00 UTC, jonathanpallant commented on xtask/src/main.rs
> +    Valid values are `python, go, cpp, swift, java, julia, c`
I would replace this list with a magic token like `$$LANG_LIST$$` and do `HELP_TEXT.replace("$$LANG_LIST$$", langs.join(", ")` this string before you print it, like:

```rust
static HELP_TEXT: &'static str = "cargo xtask

LANG:

  We support $$LANG_LIST$$
";

fn main() {
    let lang_list = ["Apples", "Bananas", "Pears"];
    println!("{}", HELP_TEXT.replace("$$LANG_LIST$$", &join_str(&lang_list)));
}

fn join_str(input: &[&str]) -> String {
    let mut output = String::new();
    let mut iter = input.iter().peekable();
    while let Some(lang) = iter.next() {
        if iter.peek().is_none() {
            output += " and ";
            output += lang;
        } else {
            output += ", ";
            output += lang;
        }
    }
    output
}
```

2025-01-06 15:04 UTC, jonathanpallant commented
There's quite a lot of code here, and coming to it fresh after vacation I lacked any real context. Some file-level comments explaining the purpose of the file and some function-level comments explaining the purpose of each function would be a useful addition.

2025-01-06 15:04 UTC, jonathanpallant commented on xtask/src/main.rs
> +    Valid values are `python, go, cpp, swift, java, julia, c`
the fancy join is optional

2025-01-06 16:51 UTC, miguelraz commented
I'll write those in later today, good point.

2025-01-06 16:51 UTC, miguelraz commented on xtask/src/main.rs
> +    Valid values are `python, go, cpp, swift, java, julia, c`
Fancy indeed. I'll work that in.

2025-01-07 02:02 UTC, miguelraz commented
@jonathanpallant this feels ready for review again.

2025-01-07 09:36 UTC, jonathanpallant requested changes

2025-01-07 09:39 UTC, jonathanpallant commented
I elected to push some changes rather than leave a bunch of review comments. Please do review the diff and let me know if you have any questions.

The final matter is deciding how we want CI to run this, to automatically check out cheatsheets. Ideally we'd have a `cargo xtask test-cheatsheets` which automatically tested all of them.

2025-01-07 14:09 UTC, miguelraz commented
All the comments being hoisted to a README make sense to me and the added level of doc comments is welcome, thanks!

I'm in favor of writing a `cargo xtask test-all`.

2025-01-07 21:56 UTC, miguelraz commented
Resolved a small merge conflict by accepting the `xtask` `target` folder as part of `.gitignore`

2025-01-08 04:21 UTC, miguelraz commented
Ah, I noticed there's a corner case I haven't handled, I'm going to work on it for a bit.

2025-01-14 10:32 UTC, merged