Kani slides
ferrous-systems/rust-training pull request #221
Opened 2024-10-24 16:26 UTC by listochkin

* What kind of bugs can we observe in Rust programs that passed compiler and Clippy checks
* Kinds of generative tests, why Kani approach (model checking is different)
* How to use Kani
* Developer experience
* Kani features, with focus on:
    * Playback - producing test cases for regression testing
    * Function contracts

2024-10-24 18:31 UTC, miguelraz commented
Did a first pass and I'm really liking it. I'm going to write down some of the stuff that could really improve this deck and come back afterwards with more concrete examples/suggestions directly into the PR.

* Numerical cancellation example - there's some more dramatic ones like a space rocket crashing or an automated car hard swerving left. There's good room to showcase a quick video here! Lemme fish one out.
* I'd like a chunkier example to finish - I think we can find something a bit more spicy than a `gcd` checker towards the end. I like it as an illustration, but I wasn't sold as "wow this tool is doing some amazing things I couldn't have done myself." Maybe even leave it as an exercise!
* In the second half of the slides I didn't see as clear a presentation of, from all the possible static analyses that could be done, the ones in which Kani could save your bacon - I think there's a good graphical way to present that succinctly.
* A great selling point for Kani is its ability to swap out different SAT solver backends, iirc. This is an unsung feature in these slides and can bring some of the model checking down from finishing in the heat death of the universe to maybe some hours. I would like to mention that.
* There's maybe a good chart that we could build towards the end on different testing crates/features/procedures and what they offer - you mention the test checkpointing (ability to save regression tests and rerun them on subsequent tests) but it would nice to also mention test case generation, test case shrinking, etc. in one neat table.

2024-10-29 10:43 UTC, tautschnig commented on training-slides/src/kani.md
> +  * Uses SAT / SMT solver to **proof** the validity of program behavior
```suggestion
  * Uses SAT / SMT solver to **prove** the validity of program behavior
```

2024-10-29 10:43 UTC, tautschnig commented on training-slides/src/kani.md
> +  * Including hidden code-paths like panics
```suggestion
  * Including hidden code paths like panics
```
(but also I don't really know what a "hidden" code path is)

2024-11-05 17:37 UTC, jonathanpallant requested changes

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +  * limited use: Standard Library and 3rd part crates have panicking code
```suggestion
  * limited use: Standard Library and 3rd party crates have panicking code
```

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +* `Clippy` has lints against well-known panicking APIs in standard library
```suggestion
* `clippy` has lints against well-known panicking APIs in the Standard Library
```

`clippy` is a command, so I think it should be in backticks. Or you could spell it "Clippy". But it should be consistent through this deck and our other decks.

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +* Static analysis tools: Clippy
```suggestion
* Static analysis tools: `clippy`
```

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +## Fuzzing
```suggestion
## Fuzz testing
```

I think this ties in better with the "XXX Testing" topics that come before and after

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +* When observes different behavior explores the related input combinations to produce the minimal test case.
```suggestion
* Observe different behaviour => explore related input combinations to produce minimal test case.
```

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +* Builds a model of all your program states
```suggestion
* Builds a model of all of your program's states
```

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +```mermaid
I could not get this graph to render in Safari or Firefox.

```text
Syntax error in graph
mermaid version 9.4.0
```

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +        * **Proofs** correctness
```suggestion
        * **Prooves** correctness
```

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +/// Test generated for harness `proofs::verify_add`
I think it might be nicer to just syntax highlight the output of the program, rather than forcing it to be presented as text. You can explain that the program produced this output.

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +## Let's fix it! VSCode
```suggestion
## Let's fix it! - VSCode
```

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +## Let's fix it! `Cargo.toml`
```suggestion
## Let's fix it! - `Cargo.toml`
```

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +## Let's fix it! `.vscode/settings.json`
```suggestion
## Let's fix it! - `.vscode/settings.json`
```

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +## Let's fix it! `*.rs`
```suggestion
## Let's fix it! - `*.rs`
```

2024-11-05 17:37 UTC, jonathanpallant commented on training-slides/src/kani.md
> +https://github.com/ferrous-systems/rust-training/tree/main/example-code/kani-hello-world
```suggestion
https://github.com/ferrous-systems/rust-training/tree/main/example-code/kani/kani-hello-world
```

I wonder if this should point at a specific git hash, in case the folder gets moved at some later date and then this link is broken.

2024-11-05 17:37 UTC, jonathanpallant commented
This is a great slide deck. I look forward to watching your presentation using it.

2024-12-10 10:17 UTC, jonathanpallant commented on training-slides/src/kani.md
> +
We need a break here because the RUN button overlaps the second block.

<img width="1377" alt="image" src="https://github.com/user-attachments/assets/b9d0e565-d193-444f-b6fb-0c7ce704b49a">

2024-12-10 10:22 UTC, jonathanpallant commented on training-slides/src/kani.md
> +https://github.com/ferrous-systems/rust-training/tree/main/example-code/kani/kani-hello-world
```suggestion
See [example-code/kani/kani-hello-world](https://github.com/ferrous-systems/rust-training/tree/main/example-code/kani/kani-hello-world)
```

The URL was a bit long otherwise.

2024-12-10 10:25 UTC, jonathanpallant commented on training-slides/src/kani.md
> +https://github.com/ferrous-systems/rust-training/tree/main/example-code/kani-hello-world
I guess if we move the code we just have to fix the link at the same time.

2024-12-13 10:27 UTC, jonathanpallant approved these changes

2024-12-13 10:27 UTC, merged